# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ccbdb8d07df6eade154a4bd00fb0d829a2a71b998095a5d2138141bbe8d207a225e86092a8584743eb3ebee757df94a618036127d40ce28ff2c101f7adafc9

test:
  secret_key_base: 925f9245b755a505297f47f33c60af1af6e2c01d6fbc77c93c96b9db9e879f32af151eebf886336ba45b672f516659e874f7f014070c027efde353d974b6edd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
